import numpy as np
print("help on numpy.add function")
help(np.add)
a=np.array([0,1,2,0])
b=np.array([1,2,3,4])
print(a)
print(b)
print("none of the elements are zero:",np.all(a))
print("none of the elements are zero:",np.all(b))
print("a>b:",np.greater(a,b))
print("a>=b:",np.greater_equal(a,b))
print("a<b:",np.less(a,b))
print("a<=b:",np.less_equal(a,b))
print("a=b:",np.equal(a,b))
print("allclose:",np.allclose(a,b))
print("zeroes array:",np.zeros(5))
print("ones array:",np.ones(5))
print("linspace:",np.linspace(1,2,3))
sum=a+b
print("tolist:",sum.tolist())
print("type:",type(sum))
print("shape:",sum.shape)
print("datatype:",sum.dtype)
